2025-09-23 18:12:49,270 - 3dmodel-app - [32mINFO[0m - 正在初始化数据库连接...
2025-09-23 18:12:49,292 - 3dmodel-app - [31mERROR[0m - 数据库连接失败: The asyncio extension requires an async driver to be used. The loaded 'pysqlite' is not async.
2025-09-23 19:25:51,199 - 3dmodel-app - [32mINFO[0m - 正在初始化数据库连接...
2025-09-23 19:25:51,236 - 3dmodel-app - [32mINFO[0m - SQL数据库连接成功
2025-09-23 19:25:51,236 - 3dmodel-app - [32mINFO[0m - 应用启动完成
